-- mysql -u root -h 35.237.254.109 -p

USE vendor;

-- Relational Model
CREATE TABLE IF NOT EXISTS Customer (
	CustomerID SERIAL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Address VARCHAR(255),
    ZipCode CHAR(5),
    Telephone CHAR(10),
    Email VARCHAR(255) NOT NULL,
    Rating INTEGER UNSIGNED,
    CreditCardNum CHAR(16),
    ItemsSold INTEGER UNSIGNED DEFAULT 0,
    ItemsPurchased INTEGER UNSIGNED DEFAULT 0,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE IF NOT EXISTS Employee (
	SSN CHAR(9),
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Address VARCHAR(255),
    ZipCode CHAR(5),
    Telephone CHAR(10),
    Email VARCHAR(255) NOT NULL,
	StartDate DATE NOT NULL,
    EmployeeLevel INTEGER NOT NULL,
    HourlyRate DECIMAL(13, 2) UNSIGNED NOT NULL,
    PRIMARY KEY (SSN)
);

CREATE TABLE IF NOT EXISTS Item (
	ItemID SERIAL,
    ItemName VARCHAR(255),
    ItemType VARCHAR(255),
    Description TEXT,
    Quantity INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (ItemID),
    FULLTEXT INDEX KeywordSearch (ItemName)
);

CREATE TABLE IF NOT EXISTS Auction (
	AuctionID SERIAL,
    BidIncrement DECIMAL(13, 2) UNSIGNED NOT NULL,
    MinBidPrice DECIMAL(13, 2) UNSIGNED NOT NULL,
    ReservePrice DECIMAL(13, 2) UNSIGNED,
    CurrentHighestBidPrice DECIMAL(13, 2) UNSIGNED,
    CurrentMaxBidPrice DECIMAL(13, 2) UNSIGNED,
    NumCopies INTEGER UNSIGNED,
    Monitor CHAR(9) NOT NULL,
    ItemID BIGINT UNSIGNED NOT NULL,
    WinnerID BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (AuctionID),
    FOREIGN KEY (Monitor) REFERENCES Employee(SSN) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Post (
	EndDate DATETIME,
    OpenDate DATETIME NOT NULL,
    CustomerID BIGINT UNSIGNED,
    AuctionID BIGINT UNSIGNED,
    PRIMARY KEY (CustomerID, AuctionID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (AuctionID) REFERENCES Auction(AuctionID) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Bid (
	CustomerID BIGINT UNSIGNED,
    AuctionID BIGINT UNSIGNED,
    BidTime DATETIME,
    BidPrice DECIMAL(13, 2) UNSIGNED NOT NULL,
    PRIMARY KEY (CustomerID, AuctionID, BidTime),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (AuctionID) REFERENCES Auction(AuctionID) ON DELETE NO ACTION ON UPDATE CASCADE
);

ALTER TABLE Auction ADD
FOREIGN KEY (AuctionID, WinnerID) REFERENCES Bid(AuctionID, CustomerID) ON DELETE NO ACTION ON UPDATE CASCADE;